name: poetry-for-neanderthals

services:
    app:
        image: ${IMAGE?}
        container_name: poetry-for-neanderthals
        restart: always
        networks:
            - traefik-public
        labels:
            - traefik.enable=true
            - traefik.http.routers.poetry-for-neanderthals.rule=Host(`poetry-for-neanderthals.aarcot.com`)
            - traefik.http.routers.poetry-for-neanderthals.entrypoints=websecure
            - traefik.http.routers.poetry-for-neanderthals.tls=true
            - traefik.http.routers.poetry-for-neanderthals.tls.certresolver=le

networks:
    traefik-public:
        external: true
